##############################################################################
# inputs for creating the plan4res dataset from IAMC inputs
##############################################################################

# list of different scenarios and years (eg. from GENeSYS-MOD results) for which we want to create a dataset
scenarios: ['LoR_Madrid_Cooking']
years: [2045]

# Regions
#######################################

# list of regions to get from data sources 
listregionsGET: ['DolAmroth','Gondor','Harad','Mordor','Rohan','World']
aggregateregions: # how to aggregate regions in plan4res dataset
    RoGonDor: ['Gondor','Mordor','Rohan']

# regional partitions in plan4res (partitions are used for coupling constraints)
partition:
    Countries: ['RoGonDor','DolAmroth','Harad']
    Continent: ['World']

technos: # list of technologies and link to modelling in plan4res
# thermal= modelled as ThermalUnit (TU), reservoir= modelled as HydroUnit (SS), 
# hydrostorage/battery=modelled as ShortTermStorage (STS), res/runofriver=modelled as IntermittentUnit (RES)
    thermal: ['Biomass|w/o CCS','Coal|Hard coal|w/o CCS','Coal|Lignite|w/o CCS','Gas|CCGT|w/o CCS','Gas|OCGT|w/o CCS','Nuclear','Oil|w/o CCS']
    reservoir: ['Hydro|Reservoir']
    hydrostorage: ['Hydro|Pumped Storage']
    battery: ['Battery|Lithium-Ion']
    res: ['Solar|PV|Rooftop|Commercial','Solar|PV|Utility|Average','Solar|PV|Utility|Inf','Solar|PV|Utility|Opt','Wind|Onshore|Avg','Wind|Onshore|Opt', 'Wind|Offshore|Deep','Wind|Offshore|Shallow','Wind|Offshore|Transitional']
    runofriver: ['Hydro|Run of River'] 
    
# list of the names of the scenarised timeseries for scenarised data 
# if using plan4res scenarised data, they are named from the meteorological year
# that was used for their creation
StochasticScenarios: ['Base','PVminus10','Demandplus10','PVminus10AndDemandplus10']

CouplingConstraints: # MaxPower and variable cost to use for creating slack units (units for non served)
    # Coupling constraints which are not listed here will not be created in dataset
    # Coupling contraints can be : Demand, Primary, Secondary, Inertia, CO2
    # For the case of CO2, MaxPower and Cost are not needed, Budget can be defined (tons/CO2)
    # Partition defines the level at which the coupling constraint applies
    ActivePowerDemand : # mandatory - demand constraint
        Partition: 'Countries'
        MaxPower : 1500000
        Cost : 10000
        SumOf: ['Cooking','ElecHeating','ElecVehicle','OtherExclHeatTranspCooking']
        #SumOf: ['Total']
    # PrimaryDemand : # optional - primary reserve constraint
        # Partition: 'Countries'
        # MaxPower : 1000
        # Cost : 15000
        # SumOf: ['Primary']
    # SecondaryDemand : # optional - primary reserve constraint
        # Partition: 'Countries'
        # MaxPower : 1000
        # Cost : 15000
        # SumOf: ['Secondary']
    # InertiaDemand : # optional - inertia constraint
        # Partition: 'Continent'
        # MaxPower : 10000
        # Cost : 15000
        # SumOf: ['Inertia']
    # PollutantBudget:
        # CO2: # optional - emissions constraints (in further versions there can be multiple gases)
            # Partition: 'Continent'
            # Budget: 100000
            # SumOf: ['CO2']

############################################################
# General parameters for dataset creation
#############################################################

# list of parameters for treating the data
ParametersCreate:
    invest: no # yes: create a dataset for the Capacity Expansion model
    zerocapacity: 1.0  # capacity in MW under which it is considered to be 0
    DynamicConstraints: no  # if 'no' the dataset will not include dynamic constraints: MinPower is set to 0, StartUpCost, MinUp and Down duration are not used
    reservoir:
        coordinated: True # DO NOT CHANGE True if you wish to optimise all reservoirs in a coordinated way, False elsewhere
        minpowerMWh: 1  # if the volume of the reservoir is lower, converted to short term storage
    InitialFillingrate:  # initial filling rates of reservoirs per countries
        Mordor : 0.5
        DolAmroth : 0.6
        Gondor : 0.7
        Harad : 0.5
        Rohan : 0.8
    # these are used when data are not available
    PumpingEfficiency:
        Compressed Air: 0.7
        Battery|Lithium-Ion: 0.7
        Battery|Redox Flow: 0.7
        Hydro|Pumped Storage: 0.8
        Hydro|Reservoir: 0.8
    Volume2CapacityRatio :  # used to compute the MaxPower or MaxVolume of storage units
        Battery|Lithium-Ion: 4
        Hydro|Pumped Storage: 100
        Hydro|Reservoir: 2000
    CapacityExpansion: # define capacity expansion dataset - list of technos which can be invested
        thermal: 
        hydrostorage:
        battery:
        res: 
        interconnections: # either define the share of maxcapacity which can be added or a list of lines with max added capacity
    conversiondollar2010euro2020: 0.978  # should be the same value than the one used below
    conversions:
        'Mt CO2/PJ':
            to: 't CO2/MWh'
        'EJ/yr': 
            to: 'MWh/yr'
        'PJ':
            to: 'MWh'
        'GW':
            to: 'MW'
        'GWh':
            to: 'MWh'
        'GWh/yr':
            to: 'MWh/yr'
        'MEUR/GW':
            to: 'EUR/MW'
        'MEUR_2020/PJ':
            to: 'MEUR/PJ'
            factor: 1
        'MEUR/PJ':
            to: 'EUR/MWh'
        'USD_2010/kW/yr':
            to: 'EUR/MW/yr'
            factor: 978
        'USD_2010/kW':
            to: 'EUR/MW'
            factor: 978
        'USD_2010/kW/yr':
            to: 'EUR/MW/yr'
            factor: 978
        'USD_2010/MWh':
            to: 'EUR/MWh'
            factor: 0.978
        'USD_2010/MWh/yr':
            to: 'EUR/MWh/yr'
            factor: 0.978
        'Mt CO2/yr':
            to: 't CO2/yr'
        'million EUR/GW':
            to: 'EUR/MW'
        'EUR_2020/kW':
            to: 'EUR/MW'
            factor: 1000
        'EUR_2020/kW/yr':
            to: 'EUR/MW/yr'
            factor: 1000
    MultFactor:  # list of technos where MaxPower is computed as energy/(mean load profile*8760)
        Hydro|Run of River : 8760
    thermal:
        NbUnitsPerTechno: 1 # if >1, the data must include unit max power for the technology and the number of units is computed as Capacity/MaxPower
        variablecost: 'Cost'  # if 'Price' the variable cost is computed as Price*Efficiency
        fuel:  # in the case of 'Price', gives the name of the correspondent fuel for which the price should be used
            Gas|Hydrogen|OCGT|w/o CHP: Gas|Hydrogen
            Gas|Hydrogen|CCGT|w/o CHP: Gas|Hydrogen

# the datagroup section lists the different 'sources' to get the data
# for each source:
# - directory and file name where to find data in case data are retrieved from 'files' (see above)
# - model, scenario, year to filter on (see openentrance data format) ; only one year is possible for plan4EU
# - regions: list of additionnal regions to retrieve (compared to listregionsGET above)	: nuts1, nuts2, nuts3, countries, ehighway
# - list of variabes to retrieve ; variables are separated into 
#		- global : global variables, not depending on technologies (eg demand, carbon price)
#		- techno : variables for which the treatment is different depending on the kind of technology, among:
#			- thermal : themal power plants
#			- reservoir : seasonal hydro storage
#			- hydrostorage : hydro short term storage
#			- battery : battery short term storage
#			- res : renewable generation (PV, windpower, run of river, ....)
#			- demandresponseloadshifting : load shifting for CS1
#	for each group, variables are separated into 3 categories, depending on the method to use for aggregating regions (add, global ie single value, mean)
# a different group must be given for annual and subannual data

listdatagroups: ['genesys_jl']

datagroups:
    genesys_jl:  # here the group with data from Open Entrance Scenario
        #inputdata: 'IAMC_Middleeast_Gondor.xlsx' 
        model: 'GENeSYS-MOD 3.2'
        regions:
            global: 'World'  # region to be used for global data
            local: []   # additional regions to include compared to general list
        subannual: no
        listvariables:
            coupling: 
                #mean: ['Price|Carbon']
                flow: ['Network|Electricity|Maximum Flow','Network|Electricity|Expansion Cost','Network|Electricity|Loss Factor']
                add: ['Final Energy|Electricity','Final Energy|Electricity|Cooking','Final Energy|Electricity|Heat','Final Energy|Electricity|Transportation','Final Energy|Electricity|Other (excl. Heat, Transport, Cooking)']
            techno:
                thermal:
                    add: ['Capacity|Electricity|','Secondary Energy|Electricity|']
                    mean: ['Variable Cost (incl. Fuel Cost)|Electricity|','Capital Cost|Electricity|','Fixed Cost|Electricity|']
                    global: ['Emission Rate|CO2|Electricity|','Lifetime|Electricity|']
                reservoir:
                    add: ['Capacity|Electricity|','Secondary Energy|Electricity|']
                hydrostorage:
                    add: ['Capacity|Electricity|','Maximum Storage|Electricity|']
                    mean: ['Capital Cost|Electricity|','Fixed Cost|Electricity|']
                    global: ['Charging Efficiency|Electricity|','Discharging Efficiency|Electricity|','Lifetime|Electricity|']
                battery:
                    add: ['Capacity|Electricity|','Maximum Storage|Electricity|']
                    mean: ['Capital Cost|Electricity|','Fixed Cost|Electricity|']
                    global: ['Charging Efficiency|Electricity|','Discharging Efficiency|Electricity|','Lifetime|Electricity|']
                res:
                    add: ['Secondary Energy|Electricity|','Capacity|Electricity|']
                    mean: ['Capital Cost|Electricity|','Fixed Cost|Electricity|']
                    global: ['Lifetime|Electricity|']
                runofriver:
                    add: ['Capacity|Electricity|','Secondary Energy|Electricity|']
                    mean: ['Capital Cost|Electricity|','Fixed Cost|Electricity|']
                    global: ['Lifetime|Electricity|']

csvfiles: # list of csv files to create in the plan4res excel file (comment line if not treated)
    ZP_ZonePartition: 'ZP_ZonePartition.csv'  # mandatory, contains description of regions
    IN_Interconnections: 'IN_Interconnections.csv'  # optionnal, contains description of network
    ZV_ZoneValues: 'ZV_ZoneValues.csv' # mandatory, contains description of coupling constraints
    TU_ThermalUnits: 'TU_ThermalUnits.csv' # optionnal, contains description of thermal units
    SS_SeasonalStorage: 'SS_SeasonalStorage.csv' # optionnal, containsescription of seasonal storages
    STS_ShortTermStorage: 'STS_ShortTermStorage.csv' # optionnal, contains description of short term storages
    RES_RenewableUnits: 'RES_RenewableUnits.csv' # optionnal, contains description of renewable units

# credentials for scenario explorer
ScenarioExplorer:
    instance: openmod4africa-internal
    user: 'user'
    password: 'pass'
    annual: no
    subannual: no

